application:
  name: Products Inventory Management

logging:
   level:
    root: INFO
    com.example.flipkart: DEBUG
   file:
    name: logs/flipkart-app.log

jwt:
 secret: simple-secret-key-123
 expiration: 86400000 # 1 day in milliseconds
server:
 port: 8080